# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedline', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='news_pic')),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.FileField(blank=True, null=True, upload_to='users_pic')),
                ('test', models.CharField(default='dalibor_test', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reguser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.RegUser')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('picture', models.FileField(blank=True, null=True, upload_to='users_pic')),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=2048)),
                ('creditcard', models.CharField(max_length=255)),
                ('short_massage', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('duration', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=255)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('training_image', models.FileField(blank=True, null=True, upload_to='.')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Trainer')),
            ],
            options={
                'verbose_name_plural': 'Training',
            },
        ),
        migrations.AddField(
            model_name='scheduletraining',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Training'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Trainer'),
        ),
        migrations.AddField(
            model_name='reguser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
