# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_rating',
            field=models.IntegerField(),
        ),
    ]
