# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 10:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20171213_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
