# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 15:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20171213_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
