# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20171213_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average_value',
            field=models.IntegerField(default=1),
        ),
    ]
