# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 16:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_rating_average_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
