# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20171213_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average_value',
        ),
        migrations.AddField(
            model_name='trainer',
            name='average_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
