# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20171214_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='average_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
