# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
