# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
