# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_auto_20190319_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='profilePicture',
            field=models.FileField(blank=True, null=True, upload_to='users_pic'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='users_pic'),
        ),
    ]
