# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-24 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_remove_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='news_pic'),
        ),
    ]
