# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='readTime',
            field=models.IntegerField(default=0),
        ),
    ]
