# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_news_readtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='readTime',
        ),
    ]
